<?php
declare(strict_types=1);

namespace Fissible\AttestLaravel\Tests\Stores;

use Fissible\AttestLaravel\Stores\EloquentChainStore;
use Fissible\AttestLaravel\Tests\TestCase;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\DB;

final class EloquentChainStoreReadTest extends TestCase
{
    use RefreshDatabase;

    private function insertCanonical(string $chainId, int $seq, string $raw): void
    {
        // envelope_id must be unique across rows; incorporate chain_id hash to avoid collisions.
        $chainSlug = substr(md5($chainId), 0, 8);
        DB::table('attest_envelopes')->insert([
            'chain_id' => $chainId,
            'sequence' => $seq,
            'envelope_id' => substr(sprintf('01H%s%015d', $chainSlug, $seq), 0, 26),
            'prev_hash' => null,
            'self_hash' => str_repeat('a', 64),
            'key_id' => 'k1',
            'type' => 't',
            'raw_envelope' => $raw,
            'created_at' => '2026-06-06 14:32:11.000000',
        ]);
    }

    public function test_exists_is_true_for_known_chain(): void
    {
        $this->insertCanonical('c', 1, $this->validEnvelope(1));
        $store = new EloquentChainStore(DB::connection(), $this->dummyLocker());
        self::assertTrue($store->exists('c'));
        self::assertFalse($store->exists('other'));
    }

    public function test_list_chains_yields_distinct_chain_ids(): void
    {
        $this->insertCanonical('c1', 1, $this->validEnvelope(1, 'c1'));
        $this->insertCanonical('c1', 2, $this->validEnvelope(2, 'c1'));
        $this->insertCanonical('c2', 1, $this->validEnvelope(1, 'c2'));
        $store = new EloquentChainStore(DB::connection(), $this->dummyLocker());
        self::assertEqualsCanonicalizing(['c1', 'c2'], iterator_to_array($store->listChains(), false));
    }

    public function test_tail_returns_highest_sequence_envelope(): void
    {
        $this->insertCanonical('c', 1, $this->validEnvelope(1));
        $this->insertCanonical('c', 2, $this->validEnvelope(2));
        $store = new EloquentChainStore(DB::connection(), $this->dummyLocker());
        $tail = $store->tail('c');
        self::assertNotNull($tail);
        self::assertSame(2, $tail->envelope->seq);
    }

    public function test_readRange_yields_envelopes_in_seq_order(): void
    {
        $this->insertCanonical('c', 1, $this->validEnvelope(1));
        $this->insertCanonical('c', 2, $this->validEnvelope(2));
        $this->insertCanonical('c', 3, $this->validEnvelope(3));
        $store = new EloquentChainStore(DB::connection(), $this->dummyLocker());
        $envs = iterator_to_array($store->readRange('c', 2, 3), false);
        self::assertCount(2, $envs);
        self::assertSame(2, $envs[0]->envelope->seq);
        self::assertSame(3, $envs[1]->envelope->seq);
    }

    public function test_readRawRange_yields_byte_identical_strings(): void
    {
        $raw = $this->validEnvelope(1);
        $this->insertCanonical('c', 1, $raw);
        $store = new EloquentChainStore(DB::connection(), $this->dummyLocker());
        $rows = iterator_to_array($store->readRawRange('c', 1), false);
        self::assertSame([$raw], $rows);
    }

    /** A valid signed-envelope JSON line that decodes via EnvelopeCodec.
     *  We don't sign for read-side tests; instead we use a fixture-style
     *  envelope generated by signing once and stored verbatim. */
    private function validEnvelope(int $seq, string $chain = 'c'): string
    {
        // Build via core's SignedEnvelope at test time so it round-trips.
        $kp = \Fissible\Attest\Signing\KeyPair::generate();
        $signer = new \Fissible\Attest\Signing\SodiumSigner($kp, keyId: 'k1');
        $env = new \Fissible\Attest\Envelope\EvidenceEnvelope(
            id: sprintf('01H%023d', $seq),
            chain: $chain,
            seq: $seq,
            ts: '2026-06-06T14:32:11.000Z',
            type: 'app.event',
            payload: ['n' => $seq],
            prevHash: null,
            keyId: 'k1',
            sigAlg: 'ed25519',
        );
        $signed = \Fissible\Attest\Envelope\SignedEnvelope::sign($env, $signer);
        return $signed->signedCanonicalBytes();
    }

    private function dummyLocker(): \Fissible\AttestLaravel\Stores\Locking\ChainLocker
    {
        // Read paths never call the locker — return a stub that throws if hit.
        return new class implements \Fissible\AttestLaravel\Stores\Locking\ChainLocker {
            public function withChainLock(string $chainId, callable $work): mixed
            {
                throw new \LogicException('locker should not be touched on read paths');
            }
        };
    }
}
